CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) UNIQUE
);

INSERT INTO users (name) VALUES ('Admin')
ON CONFLICT (name) DO NOTHING;

INSERT INTO users (name) VALUES ('User')
ON CONFLICT (name) DO NOTHING;
